# Generated by Django 3.2.25 on 2024-07-30 12:46

import django.core.validators
from django.db import migrations, models
import djongo.storage
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255, unique=True)),
                ('file_summary', models.TextField(blank=True)),
                ('file', models.FileField(storage=djongo.storage.GridFSStorage(base_url='http://localhost:8000/myfiles/', collection='myfiles'), upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'pptx'])])),
            ],
        ),
    ]
